services:
    medusa-store:
        build:
            context: ./medusa-store
            dockerfile: Dockerfile
        image: medusa-store:test
        container_name: medusa-store
        depends_on:
            - postgres
            - redis
        environment:
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
            REDIS_URL: redis://cache
            NODE_ENV: development
            JWT_SECRET: some_jwt_secret
            COOKIE_SECRET: some_cookie_secret
            PORT: 9000
        volumes:
            - ./medusa-store:/app/medusa
        ports:
            - "9000:9000"
        networks:
            - medusapostgressnetwork
    postgres:
        image: postgres:10.4
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: medusa-docker
            PGDATA: /var/lib/postgresql/data/medusa/
        networks:
            - medusapostgressnetwork
        volumes:
            - pgmedusadata:/var/lib/postgresql/data/medusa
    redis:
        image: redis
        container_name: cache
        expose:
            - 6379
        networks:
            - medusapostgressnetwork
networks:
    medusapostgressnetwork:
        name: medusapostgressnetwork
        driver: bridge
volumes:
    pgmedusadata:
    medusa-store:
