services:
    medusa-store:
        build:
            context: ./medusa-store
            dockerfile: Dockerfile
        image: medusa-store:test
        container_name: medusa-server
        depends_on:
            - postgres
            - redis
        environment:
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
            REDIS_URL: redis://cache
            NODE_ENV: development
            JWT_SECRET: some_jwt_secret
            COOKIE_SECRET: some_cookie_secret
            PORT: 9000

    postgres:
        image: postgres:10.4
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: medusa-docker

    redis:
        image: redis
        container_name: cache
        expose:
            - 6379

    # admin:
    #     build:
    #         context: ./medusa-store
    #         dockerfile: Dockerfile.admin
    #     image: admin:test
    #     depends_on:
    #         - medusa-store
    #     container_name: medusa-admin
    #     environment:
    #         NODE_OPTIONS: --openssl-legacy-provider

    # ebclientnext:
    #     build:
    #         context: ./ebclientnext
    #         dockerfile: Dockerfile
    #     image: ebclientnext:test
    #     container_name: medusa-ebclientnext
    #     depends_on:
    #         - medusa-store
